// Listener cities schema and types

export interface ListenerCity {
  id: string;
  city: string;
  stateProvince?: string; // Optional - not all countries have states/provinces
  country: string;
  continent: string;
  region?: string; // e.g., "North America", "Western Europe"
  isCovered: boolean; // Has it been covered on "Where the fuck are the viewers from"
  coveredDate?: string;
  coveredEpisode?: string;
  createdAt: string;
  updatedAt: string;
  profileId: string;
}

export interface ListenerCityInput {
  city: string;
  stateProvince?: string;
  country?: string; // Optional - will be auto-detected if not provided
}

export interface CityImportResult {
  success: boolean;
  imported: number;
  failed: number;
  errors: Array<{
    row: number;
    city: string;
    error: string;
  }>;
}

// Continent mapping for countries (comprehensive list of 150+ countries)
export const COUNTRY_TO_CONTINENT: Record<string, string> = {
  // ===== NORTH AMERICA =====
  'USA': 'North America',
  'United States': 'North America',
  'US': 'North America',
  'Canada': 'North America',
  'Mexico': 'North America',
  'Guatemala': 'North America',
  'Honduras': 'North America',
  'El Salvador': 'North America',
  'Nicaragua': 'North America',
  'Costa Rica': 'North America',
  'Panama': 'North America',
  'Belize': 'North America',
  
  // Caribbean
  'Cuba': 'North America',
  'Jamaica': 'North America',
  'Haiti': 'North America',
  'Dominican Republic': 'North America',
  'Puerto Rico': 'North America',
  'Trinidad and Tobago': 'North America',
  'Bahamas': 'North America',
  'Barbados': 'North America',
  
  // ===== SOUTH AMERICA =====
  'Brazil': 'South America',
  'Argentina': 'South America',
  'Chile': 'South America',
  'Colombia': 'South America',
  'Peru': 'South America',
  'Venezuela': 'South America',
  'Ecuador': 'South America',
  'Bolivia': 'South America',
  'Paraguay': 'South America',
  'Uruguay': 'South America',
  'Guyana': 'South America',
  'Suriname': 'South America',
  'French Guiana': 'South America',
  
  // ===== WESTERN EUROPE =====
  'UK': 'Europe',
  'United Kingdom': 'Europe',
  'England': 'Europe',
  'Scotland': 'Europe',
  'Wales': 'Europe',
  'Northern Ireland': 'Europe',
  'Ireland': 'Europe',
  'France': 'Europe',
  'Germany': 'Europe',
  'Netherlands': 'Europe',
  'Belgium': 'Europe',
  'Luxembourg': 'Europe',
  'Switzerland': 'Europe',
  'Austria': 'Europe',
  'Liechtenstein': 'Europe',
  'Monaco': 'Europe',
  
  // Southern Europe
  'Spain': 'Europe',
  'Portugal': 'Europe',
  'Italy': 'Europe',
  'Greece': 'Europe',
  'Malta': 'Europe',
  'Cyprus': 'Europe',
  'Vatican City': 'Europe',
  'San Marino': 'Europe',
  'Andorra': 'Europe',
  
  // Northern Europe
  'Sweden': 'Europe',
  'Norway': 'Europe',
  'Denmark': 'Europe',
  'Finland': 'Europe',
  'Iceland': 'Europe',
  
  // Eastern Europe
  'Poland': 'Europe',
  'Czech Republic': 'Europe',
  'Slovakia': 'Europe',
  'Hungary': 'Europe',
  'Romania': 'Europe',
  'Bulgaria': 'Europe',
  'Serbia': 'Europe',
  'Croatia': 'Europe',
  'Slovenia': 'Europe',
  'Bosnia and Herzegovina': 'Europe',
  'Montenegro': 'Europe',
  'North Macedonia': 'Europe',
  'Albania': 'Europe',
  'Kosovo': 'Europe',
  'Lithuania': 'Europe',
  'Latvia': 'Europe',
  'Estonia': 'Europe',
  'Belarus': 'Europe',
  'Ukraine': 'Europe',
  'Moldova': 'Europe',
  'Russia': 'Europe',
  
  // ===== ASIA =====
  // East Asia
  'China': 'Asia',
  'Japan': 'Asia',
  'South Korea': 'Asia',
  'North Korea': 'Asia',
  'Taiwan': 'Asia',
  'Mongolia': 'Asia',
  
  // Southeast Asia
  'Thailand': 'Asia',
  'Vietnam': 'Asia',
  'Philippines': 'Asia',
  'Indonesia': 'Asia',
  'Malaysia': 'Asia',
  'Singapore': 'Asia',
  'Myanmar': 'Asia',
  'Cambodia': 'Asia',
  'Laos': 'Asia',
  'Brunei': 'Asia',
  'Timor-Leste': 'Asia',
  
  // South Asia
  'India': 'Asia',
  'Pakistan': 'Asia',
  'Bangladesh': 'Asia',
  'Sri Lanka': 'Asia',
  'Nepal': 'Asia',
  'Bhutan': 'Asia',
  'Maldives': 'Asia',
  'Afghanistan': 'Asia',
  
  // Central Asia
  'Kazakhstan': 'Asia',
  'Uzbekistan': 'Asia',
  'Turkmenistan': 'Asia',
  'Kyrgyzstan': 'Asia',
  'Tajikistan': 'Asia',
  
  // Middle East
  'Turkey': 'Asia',
  'Iran': 'Asia',
  'Iraq': 'Asia',
  'Saudi Arabia': 'Asia',
  'Yemen': 'Asia',
  'Oman': 'Asia',
  'United Arab Emirates': 'Asia',
  'UAE': 'Asia',
  'Qatar': 'Asia',
  'Kuwait': 'Asia',
  'Bahrain': 'Asia',
  'Jordan': 'Asia',
  'Lebanon': 'Asia',
  'Syria': 'Asia',
  'Israel': 'Asia',
  'Palestine': 'Asia',
  'Armenia': 'Asia',
  'Azerbaijan': 'Asia',
  'Georgia': 'Asia',
  
  // ===== AFRICA =====
  // North Africa
  'Egypt': 'Africa',
  'Libya': 'Africa',
  'Tunisia': 'Africa',
  'Algeria': 'Africa',
  'Morocco': 'Africa',
  'Sudan': 'Africa',
  
  // West Africa
  'Nigeria': 'Africa',
  'Ghana': 'Africa',
  'Ivory Coast': 'Africa',
  'Senegal': 'Africa',
  'Mali': 'Africa',
  'Burkina Faso': 'Africa',
  'Niger': 'Africa',
  'Guinea': 'Africa',
  'Benin': 'Africa',
  'Togo': 'Africa',
  'Sierra Leone': 'Africa',
  'Liberia': 'Africa',
  'Mauritania': 'Africa',
  'Gambia': 'Africa',
  'Cape Verde': 'Africa',
  
  // East Africa
  'Kenya': 'Africa',
  'Tanzania': 'Africa',
  'Uganda': 'Africa',
  'Ethiopia': 'Africa',
  'Somalia': 'Africa',
  'Eritrea': 'Africa',
  'Djibouti': 'Africa',
  'Rwanda': 'Africa',
  'Burundi': 'Africa',
  
  // Central Africa
  'Democratic Republic of the Congo': 'Africa',
  'Republic of the Congo': 'Africa',
  'Central African Republic': 'Africa',
  'Chad': 'Africa',
  'Cameroon': 'Africa',
  'Gabon': 'Africa',
  'Equatorial Guinea': 'Africa',
  
  // Southern Africa
  'South Africa': 'Africa',
  'Zimbabwe': 'Africa',
  'Zambia': 'Africa',
  'Mozambique': 'Africa',
  'Botswana': 'Africa',
  'Namibia': 'Africa',
  'Angola': 'Africa',
  'Malawi': 'Africa',
  'Lesotho': 'Africa',
  'Eswatini': 'Africa',
  'Madagascar': 'Africa',
  'Mauritius': 'Africa',
  
  // ===== OCEANIA =====
  'Australia': 'Oceania',
  'New Zealand': 'Oceania',
  'Papua New Guinea': 'Oceania',
  'Fiji': 'Oceania',
  'Solomon Islands': 'Oceania',
  'Vanuatu': 'Oceania',
  'Samoa': 'Oceania',
  'Tonga': 'Oceania',
  'Micronesia': 'Oceania',
  'Palau': 'Oceania',
  'Marshall Islands': 'Oceania',
  'Kiribati': 'Oceania',
  'Nauru': 'Oceania',
  'Tuvalu': 'Oceania',
};

// US States mapping (full name and abbreviation)
export const US_STATES: Record<string, string> = {
  'Alabama': 'Alabama', 'AL': 'Alabama',
  'Alaska': 'Alaska', 'AK': 'Alaska',
  'Arizona': 'Arizona', 'AZ': 'Arizona',
  'Arkansas': 'Arkansas', 'AR': 'Arkansas',
  'California': 'California', 'CA': 'California',
  'Colorado': 'Colorado', 'CO': 'Colorado',
  'Connecticut': 'Connecticut', 'CT': 'Connecticut',
  'Delaware': 'Delaware', 'DE': 'Delaware',
  'Florida': 'Florida', 'FL': 'Florida',
  'Georgia': 'Georgia', 'GA': 'Georgia',
  'Hawaii': 'Hawaii', 'HI': 'Hawaii',
  'Idaho': 'Idaho', 'ID': 'Idaho',
  'Illinois': 'Illinois', 'IL': 'Illinois',
  'Indiana': 'Indiana', 'IN': 'Indiana',
  'Iowa': 'Iowa', 'IA': 'Iowa',
  'Kansas': 'Kansas', 'KS': 'Kansas',
  'Kentucky': 'Kentucky', 'KY': 'Kentucky',
  'Louisiana': 'Louisiana', 'LA': 'Louisiana',
  'Maine': 'Maine', 'ME': 'Maine',
  'Maryland': 'Maryland', 'MD': 'Maryland',
  'Massachusetts': 'Massachusetts', 'MA': 'Massachusetts',
  'Michigan': 'Michigan', 'MI': 'Michigan',
  'Minnesota': 'Minnesota', 'MN': 'Minnesota',
  'Mississippi': 'Mississippi', 'MS': 'Mississippi',
  'Missouri': 'Missouri', 'MO': 'Missouri',
  'Montana': 'Montana', 'MT': 'Montana',
  'Nebraska': 'Nebraska', 'NE': 'Nebraska',
  'Nevada': 'Nevada', 'NV': 'Nevada',
  'New Hampshire': 'New Hampshire', 'NH': 'New Hampshire',
  'New Jersey': 'New Jersey', 'NJ': 'New Jersey',
  'New Mexico': 'New Mexico', 'NM': 'New Mexico',
  'New York': 'New York', 'NY': 'New York',
  'North Carolina': 'North Carolina', 'NC': 'North Carolina',
  'North Dakota': 'North Dakota', 'ND': 'North Dakota',
  'Ohio': 'Ohio', 'OH': 'Ohio',
  'Oklahoma': 'Oklahoma', 'OK': 'Oklahoma',
  'Oregon': 'Oregon', 'OR': 'Oregon',
  'Pennsylvania': 'Pennsylvania', 'PA': 'Pennsylvania',
  'Rhode Island': 'Rhode Island', 'RI': 'Rhode Island',
  'South Carolina': 'South Carolina', 'SC': 'South Carolina',
  'South Dakota': 'South Dakota', 'SD': 'South Dakota',
  'Tennessee': 'Tennessee', 'TN': 'Tennessee',
  'Texas': 'Texas', 'TX': 'Texas',
  'Utah': 'Utah', 'UT': 'Utah',
  'Vermont': 'Vermont', 'VT': 'Vermont',
  'Virginia': 'Virginia', 'VA': 'Virginia',
  'Washington': 'Washington', 'WA': 'Washington',
  'West Virginia': 'West Virginia', 'WV': 'West Virginia',
  'Wisconsin': 'Wisconsin', 'WI': 'Wisconsin',
  'Wyoming': 'Wyoming', 'WY': 'Wyoming',
  'District of Columbia': 'District of Columbia', 'DC': 'District of Columbia',
};

// Canadian Provinces mapping (full name and abbreviation)
export const CANADIAN_PROVINCES: Record<string, string> = {
  'Alberta': 'Alberta', 'AB': 'Alberta',
  'British Columbia': 'British Columbia', 'BC': 'British Columbia',
  'Manitoba': 'Manitoba', 'MB': 'Manitoba',
  'New Brunswick': 'New Brunswick', 'NB': 'New Brunswick',
  'Newfoundland and Labrador': 'Newfoundland and Labrador', 'NL': 'Newfoundland and Labrador',
  'Northwest Territories': 'Northwest Territories', 'NT': 'Northwest Territories',
  'Nova Scotia': 'Nova Scotia', 'NS': 'Nova Scotia',
  'Nunavut': 'Nunavut', 'NU': 'Nunavut',
  'Ontario': 'Ontario', 'ON': 'Ontario',
  'Prince Edward Island': 'Prince Edward Island', 'PE': 'Prince Edward Island',
  'Quebec': 'Quebec', 'QC': 'Quebec',
  'Saskatchewan': 'Saskatchewan', 'SK': 'Saskatchewan',
  'Yukon': 'Yukon', 'YT': 'Yukon',
};

// Well-known cities that can help auto-detect country (500+ major world cities)
export const FAMOUS_CITIES: Record<string, { country: string; stateProvince?: string }> = {
  // ===== UNITED STATES =====
  'New York': { country: 'USA', stateProvince: 'New York' },
  'Los Angeles': { country: 'USA', stateProvince: 'California' },
  'Chicago': { country: 'USA', stateProvince: 'Illinois' },
  'Houston': { country: 'USA', stateProvince: 'Texas' },
  'Phoenix': { country: 'USA', stateProvince: 'Arizona' },
  'Philadelphia': { country: 'USA', stateProvince: 'Pennsylvania' },
  'San Antonio': { country: 'USA', stateProvince: 'Texas' },
  'San Diego': { country: 'USA', stateProvince: 'California' },
  'Dallas': { country: 'USA', stateProvince: 'Texas' },
  'San Jose': { country: 'USA', stateProvince: 'California' },
  'Austin': { country: 'USA', stateProvince: 'Texas' },
  'Jacksonville': { country: 'USA', stateProvince: 'Florida' },
  'Fort Worth': { country: 'USA', stateProvince: 'Texas' },
  'Columbus': { country: 'USA', stateProvince: 'Ohio' },
  'Charlotte': { country: 'USA', stateProvince: 'North Carolina' },
  'San Francisco': { country: 'USA', stateProvince: 'California' },
  'Indianapolis': { country: 'USA', stateProvince: 'Indiana' },
  'Seattle': { country: 'USA', stateProvince: 'Washington' },
  'Denver': { country: 'USA', stateProvince: 'Colorado' },
  'Washington': { country: 'USA', stateProvince: 'District of Columbia' },
  'Boston': { country: 'USA', stateProvince: 'Massachusetts' },
  'El Paso': { country: 'USA', stateProvince: 'Texas' },
  'Detroit': { country: 'USA', stateProvince: 'Michigan' },
  'Nashville': { country: 'USA', stateProvince: 'Tennessee' },
  'Portland': { country: 'USA', stateProvince: 'Oregon' },
  'Memphis': { country: 'USA', stateProvince: 'Tennessee' },
  'Oklahoma City': { country: 'USA', stateProvince: 'Oklahoma' },
  'Las Vegas': { country: 'USA', stateProvince: 'Nevada' },
  'Louisville': { country: 'USA', stateProvince: 'Kentucky' },
  'Baltimore': { country: 'USA', stateProvince: 'Maryland' },
  'Milwaukee': { country: 'USA', stateProvince: 'Wisconsin' },
  'Albuquerque': { country: 'USA', stateProvince: 'New Mexico' },
  'Tucson': { country: 'USA', stateProvince: 'Arizona' },
  'Fresno': { country: 'USA', stateProvince: 'California' },
  'Sacramento': { country: 'USA', stateProvince: 'California' },
  'Kansas City': { country: 'USA', stateProvince: 'Missouri' },
  'Mesa': { country: 'USA', stateProvince: 'Arizona' },
  'Atlanta': { country: 'USA', stateProvince: 'Georgia' },
  'Miami': { country: 'USA', stateProvince: 'Florida' },
  'Raleigh': { country: 'USA', stateProvince: 'North Carolina' },
  'Omaha': { country: 'USA', stateProvince: 'Nebraska' },
  'Colorado Springs': { country: 'USA', stateProvince: 'Colorado' },
  'Virginia Beach': { country: 'USA', stateProvince: 'Virginia' },
  'Oakland': { country: 'USA', stateProvince: 'California' },
  'Minneapolis': { country: 'USA', stateProvince: 'Minnesota' },
  'Tulsa': { country: 'USA', stateProvince: 'Oklahoma' },
  'Tampa': { country: 'USA', stateProvince: 'Florida' },
  'Arlington': { country: 'USA', stateProvince: 'Texas' },
  'New Orleans': { country: 'USA', stateProvince: 'Louisiana' },
  
  // ===== CANADA =====
  'Toronto': { country: 'Canada', stateProvince: 'Ontario' },
  'Montreal': { country: 'Canada', stateProvince: 'Quebec' },
  'Vancouver': { country: 'Canada', stateProvince: 'British Columbia' },
  'Calgary': { country: 'Canada', stateProvince: 'Alberta' },
  'Edmonton': { country: 'Canada', stateProvince: 'Alberta' },
  'Ottawa': { country: 'Canada', stateProvince: 'Ontario' },
  'Winnipeg': { country: 'Canada', stateProvince: 'Manitoba' },
  'Quebec City': { country: 'Canada', stateProvince: 'Quebec' },
  'Hamilton': { country: 'Canada', stateProvince: 'Ontario' },
  'Kitchener': { country: 'Canada', stateProvince: 'Ontario' },
  'Halifax': { country: 'Canada', stateProvince: 'Nova Scotia' },
  'Victoria': { country: 'Canada', stateProvince: 'British Columbia' },
  
  // ===== MEXICO & CENTRAL AMERICA =====
  'Mexico City': { country: 'Mexico' },
  'Guadalajara': { country: 'Mexico' },
  'Monterrey': { country: 'Mexico' },
  'Tijuana': { country: 'Mexico' },
  'Cancún': { country: 'Mexico' },
  'Puebla': { country: 'Mexico' },
  'Guatemala City': { country: 'Guatemala' },
  'San Salvador': { country: 'El Salvador' },
  'Managua': { country: 'Nicaragua' },
  'San José': { country: 'Costa Rica' },
  'Panama City': { country: 'Panama' },
  
  // ===== CARIBBEAN =====
  'Havana': { country: 'Cuba' },
  'Kingston': { country: 'Jamaica' },
  'Santo Domingo': { country: 'Dominican Republic' },
  'Port-au-Prince': { country: 'Haiti' },
  'San Juan': { country: 'Puerto Rico' },
  
  // ===== SOUTH AMERICA =====
  'São Paulo': { country: 'Brazil' },
  'Rio de Janeiro': { country: 'Brazil' },
  'Brasília': { country: 'Brazil' },
  'Salvador': { country: 'Brazil' },
  'Fortaleza': { country: 'Brazil' },
  'Belo Horizonte': { country: 'Brazil' },
  'Manaus': { country: 'Brazil' },
  'Buenos Aires': { country: 'Argentina' },
  'Córdoba': { country: 'Argentina' },
  'Rosario': { country: 'Argentina' },
  'Lima': { country: 'Peru' },
  'Bogotá': { country: 'Colombia' },
  'Medellín': { country: 'Colombia' },
  'Cali': { country: 'Colombia' },
  'Santiago': { country: 'Chile' },
  'Caracas': { country: 'Venezuela' },
  'Quito': { country: 'Ecuador' },
  'Guayaquil': { country: 'Ecuador' },
  'La Paz': { country: 'Bolivia' },
  'Montevideo': { country: 'Uruguay' },
  
  // ===== UNITED KINGDOM =====
  'London': { country: 'UK' },
  'Manchester': { country: 'UK' },
  'Birmingham': { country: 'UK' },
  'Liverpool': { country: 'UK' },
  'Leeds': { country: 'UK' },
  'Sheffield': { country: 'UK' },
  'Edinburgh': { country: 'UK' },
  'Glasgow': { country: 'UK' },
  'Bristol': { country: 'UK' },
  'Newcastle': { country: 'UK' },
  'Cardiff': { country: 'UK' },
  'Belfast': { country: 'UK' },
  'Nottingham': { country: 'UK' },
  'Southampton': { country: 'UK' },
  
  // ===== WESTERN EUROPE =====
  'Paris': { country: 'France' },
  'Marseille': { country: 'France' },
  'Lyon': { country: 'France' },
  'Toulouse': { country: 'France' },
  'Nice': { country: 'France' },
  'Nantes': { country: 'France' },
  'Berlin': { country: 'Germany' },
  'Hamburg': { country: 'Germany' },
  'Munich': { country: 'Germany' },
  'Cologne': { country: 'Germany' },
  'Frankfurt': { country: 'Germany' },
  'Stuttgart': { country: 'Germany' },
  'Düsseldorf': { country: 'Germany' },
  'Amsterdam': { country: 'Netherlands' },
  'Rotterdam': { country: 'Netherlands' },
  'The Hague': { country: 'Netherlands' },
  'Utrecht': { country: 'Netherlands' },
  'Brussels': { country: 'Belgium' },
  'Antwerp': { country: 'Belgium' },
  'Zurich': { country: 'Switzerland' },
  'Geneva': { country: 'Switzerland' },
  'Basel': { country: 'Switzerland' },
  'Vienna': { country: 'Austria' },
  'Luxembourg': { country: 'Luxembourg' },
  
  // ===== SOUTHERN EUROPE =====
  'Rome': { country: 'Italy' },
  'Milan': { country: 'Italy' },
  'Naples': { country: 'Italy' },
  'Turin': { country: 'Italy' },
  'Florence': { country: 'Italy' },
  'Venice': { country: 'Italy' },
  'Madrid': { country: 'Spain' },
  'Barcelona': { country: 'Spain' },
  'Valencia': { country: 'Spain' },
  'Seville': { country: 'Spain' },
  'Bilbao': { country: 'Spain' },
  'Lisbon': { country: 'Portugal' },
  'Porto': { country: 'Portugal' },
  'Athens': { country: 'Greece' },
  'Thessaloniki': { country: 'Greece' },
  
  // ===== NORTHERN EUROPE =====
  'Stockholm': { country: 'Sweden' },
  'Gothenburg': { country: 'Sweden' },
  'Oslo': { country: 'Norway' },
  'Copenhagen': { country: 'Denmark' },
  'Helsinki': { country: 'Finland' },
  'Reykjavik': { country: 'Iceland' },
  
  // ===== EASTERN EUROPE =====
  'Warsaw': { country: 'Poland' },
  'Kraków': { country: 'Poland' },
  'Prague': { country: 'Czech Republic' },
  'Budapest': { country: 'Hungary' },
  'Bucharest': { country: 'Romania' },
  'Sofia': { country: 'Bulgaria' },
  'Belgrade': { country: 'Serbia' },
  'Zagreb': { country: 'Croatia' },
  'Bratislava': { country: 'Slovakia' },
  'Vilnius': { country: 'Lithuania' },
  'Riga': { country: 'Latvia' },
  'Tallinn': { country: 'Estonia' },
  
  // ===== RUSSIA & FORMER USSR =====
  'Moscow': { country: 'Russia' },
  'Saint Petersburg': { country: 'Russia' },
  'Novosibirsk': { country: 'Russia' },
  'Yekaterinburg': { country: 'Russia' },
  'Nizhny Novgorod': { country: 'Russia' },
  'Kazan': { country: 'Russia' },
  'Kiev': { country: 'Ukraine' },
  'Kyiv': { country: 'Ukraine' },
  'Kharkiv': { country: 'Ukraine' },
  'Odessa': { country: 'Ukraine' },
  
  // ===== MIDDLE EAST =====
  'Istanbul': { country: 'Turkey' },
  'Ankara': { country: 'Turkey' },
  'Izmir': { country: 'Turkey' },
  'Dubai': { country: 'United Arab Emirates' },
  'Abu Dhabi': { country: 'United Arab Emirates' },
  'Riyadh': { country: 'Saudi Arabia' },
  'Jeddah': { country: 'Saudi Arabia' },
  'Mecca': { country: 'Saudi Arabia' },
  'Tehran': { country: 'Iran' },
  'Baghdad': { country: 'Iraq' },
  'Tel Aviv': { country: 'Israel' },
  'Jerusalem': { country: 'Israel' },
  'Beirut': { country: 'Lebanon' },
  'Damascus': { country: 'Syria' },
  'Amman': { country: 'Jordan' },
  'Doha': { country: 'Qatar' },
  'Kuwait City': { country: 'Kuwait' },
  'Muscat': { country: 'Oman' },
  
  // ===== EAST ASIA =====
  'Tokyo': { country: 'Japan' },
  'Yokohama': { country: 'Japan' },
  'Osaka': { country: 'Japan' },
  'Nagoya': { country: 'Japan' },
  'Sapporo': { country: 'Japan' },
  'Fukuoka': { country: 'Japan' },
  'Kyoto': { country: 'Japan' },
  'Beijing': { country: 'China' },
  'Shanghai': { country: 'China' },
  'Guangzhou': { country: 'China' },
  'Shenzhen': { country: 'China' },
  'Chengdu': { country: 'China' },
  'Chongqing': { country: 'China' },
  'Tianjin': { country: 'China' },
  'Wuhan': { country: 'China' },
  'Hangzhou': { country: 'China' },
  'Xi\'an': { country: 'China' },
  'Hong Kong': { country: 'China' },
  'Seoul': { country: 'South Korea' },
  'Busan': { country: 'South Korea' },
  'Incheon': { country: 'South Korea' },
  'Taipei': { country: 'Taiwan' },
  
  // ===== SOUTHEAST ASIA =====
  'Bangkok': { country: 'Thailand' },
  'Singapore': { country: 'Singapore' },
  'Jakarta': { country: 'Indonesia' },
  'Surabaya': { country: 'Indonesia' },
  'Bandung': { country: 'Indonesia' },
  'Manila': { country: 'Philippines' },
  'Quezon City': { country: 'Philippines' },
  'Ho Chi Minh City': { country: 'Vietnam' },
  'Hanoi': { country: 'Vietnam' },
  'Kuala Lumpur': { country: 'Malaysia' },
  'Yangon': { country: 'Myanmar' },
  'Phnom Penh': { country: 'Cambodia' },
  'Vientiane': { country: 'Laos' },
  'Brunei': { country: 'Brunei' },
  
  // ===== SOUTH ASIA =====
  'Mumbai': { country: 'India' },
  'Delhi': { country: 'India' },
  'Bangalore': { country: 'India' },
  'Hyderabad': { country: 'India' },
  'Ahmedabad': { country: 'India' },
  'Chennai': { country: 'India' },
  'Kolkata': { country: 'India' },
  'Pune': { country: 'India' },
  'Jaipur': { country: 'India' },
  'Karachi': { country: 'Pakistan' },
  'Lahore': { country: 'Pakistan' },
  'Islamabad': { country: 'Pakistan' },
  'Dhaka': { country: 'Bangladesh' },
  'Colombo': { country: 'Sri Lanka' },
  'Kathmandu': { country: 'Nepal' },
  
  // ===== OCEANIA =====
  'Sydney': { country: 'Australia', stateProvince: 'New South Wales' },
  'Melbourne': { country: 'Australia', stateProvince: 'Victoria' },
  'Brisbane': { country: 'Australia', stateProvince: 'Queensland' },
  'Perth': { country: 'Australia', stateProvince: 'Western Australia' },
  'Adelaide': { country: 'Australia', stateProvince: 'South Australia' },
  'Gold Coast': { country: 'Australia', stateProvince: 'Queensland' },
  'Canberra': { country: 'Australia', stateProvince: 'Australian Capital Territory' },
  'Auckland': { country: 'New Zealand' },
  'Wellington': { country: 'New Zealand' },
  'Christchurch': { country: 'New Zealand' },
  
  // ===== AFRICA =====
  'Cairo': { country: 'Egypt' },
  'Alexandria': { country: 'Egypt' },
  'Lagos': { country: 'Nigeria' },
  'Kano': { country: 'Nigeria' },
  'Johannesburg': { country: 'South Africa' },
  'Cape Town': { country: 'South Africa' },
  'Durban': { country: 'South Africa' },
  'Nairobi': { country: 'Kenya' },
  'Addis Ababa': { country: 'Ethiopia' },
  'Accra': { country: 'Ghana' },
  'Casablanca': { country: 'Morocco' },
  'Algiers': { country: 'Algeria' },
  'Tunis': { country: 'Tunisia' },
  'Dakar': { country: 'Senegal' },
  'Dar es Salaam': { country: 'Tanzania' },
  'Kampala': { country: 'Uganda' },
  'Luanda': { country: 'Angola' },
  'Khartoum': { country: 'Sudan' },
  'Abidjan': { country: 'Ivory Coast' },
  'Kinshasa': { country: 'Democratic Republic of the Congo' },
  
  // ===== MORE US CITIES (by state) =====
  'Montgomery': { country: 'USA', stateProvince: 'Alabama' },
  'Mobile': { country: 'USA', stateProvince: 'Alabama' },
  'Anchorage': { country: 'USA', stateProvince: 'Alaska' },
  'Fairbanks': { country: 'USA', stateProvince: 'Alaska' },
  'Juneau': { country: 'USA', stateProvince: 'Alaska' },
  'Chandler': { country: 'USA', stateProvince: 'Arizona' },
  'Scottsdale': { country: 'USA', stateProvince: 'Arizona' },
  'Gilbert': { country: 'USA', stateProvince: 'Arizona' },
  'Tempe': { country: 'USA', stateProvince: 'Arizona' },
  'Little Rock': { country: 'USA', stateProvince: 'Arkansas' },
  'Fayetteville': { country: 'USA', stateProvince: 'Arkansas' },
  'Long Beach': { country: 'USA', stateProvince: 'California' },
  'Anaheim': { country: 'USA', stateProvince: 'California' },
  'Santa Ana': { country: 'USA', stateProvince: 'California' },
  'Riverside': { country: 'USA', stateProvince: 'California' },
  'Stockton': { country: 'USA', stateProvince: 'California' },
  'Irvine': { country: 'USA', stateProvince: 'California' },
  'Bakersfield': { country: 'USA', stateProvince: 'California' },
  'Fremont': { country: 'USA', stateProvince: 'California' },
  'San Bernardino': { country: 'USA', stateProvince: 'California' },
  'Modesto': { country: 'USA', stateProvince: 'California' },
  'Fontana': { country: 'USA', stateProvince: 'California' },
  'Santa Clarita': { country: 'USA', stateProvince: 'California' },
  'Aurora': { country: 'USA', stateProvince: 'Colorado' },
  'Fort Collins': { country: 'USA', stateProvince: 'Colorado' },
  'Lakewood': { country: 'USA', stateProvince: 'Colorado' },
  'Boulder': { country: 'USA', stateProvince: 'Colorado' },
  'Bridgeport': { country: 'USA', stateProvince: 'Connecticut' },
  'New Haven': { country: 'USA', stateProvince: 'Connecticut' },
  'Hartford': { country: 'USA', stateProvince: 'Connecticut' },
  'Wilmington': { country: 'USA', stateProvince: 'Delaware' },
  'Dover': { country: 'USA', stateProvince: 'Delaware' },
  'Orlando': { country: 'USA', stateProvince: 'Florida' },
  'St. Petersburg': { country: 'USA', stateProvince: 'Florida' },
  'Hialeah': { country: 'USA', stateProvince: 'Florida' },
  'Tallahassee': { country: 'USA', stateProvince: 'Florida' },
  'Fort Lauderdale': { country: 'USA', stateProvince: 'Florida' },
  'Port St. Lucie': { country: 'USA', stateProvince: 'Florida' },
  'Cape Coral': { country: 'USA', stateProvince: 'Florida' },
  'Pembroke Pines': { country: 'USA', stateProvince: 'Florida' },
  'Gainesville': { country: 'USA', stateProvince: 'Florida' },
  'Savannah': { country: 'USA', stateProvince: 'Georgia' },
  'Honolulu': { country: 'USA', stateProvince: 'Hawaii' },
  'Boise': { country: 'USA', stateProvince: 'Idaho' },
  'Nampa': { country: 'USA', stateProvince: 'Idaho' },
  'Naperville': { country: 'USA', stateProvince: 'Illinois' },
  'Rockford': { country: 'USA', stateProvince: 'Illinois' },
  'Joliet': { country: 'USA', stateProvince: 'Illinois' },
  'Springfield': { country: 'USA', stateProvince: 'Illinois' },
  'Peoria': { country: 'USA', stateProvince: 'Illinois' },
  'Evansville': { country: 'USA', stateProvince: 'Indiana' },
  'South Bend': { country: 'USA', stateProvince: 'Indiana' },
  'Cedar Rapids': { country: 'USA', stateProvince: 'Iowa' },
  'Davenport': { country: 'USA', stateProvince: 'Iowa' },
  'Des Moines': { country: 'USA', stateProvince: 'Iowa' },
  'Wichita': { country: 'USA', stateProvince: 'Kansas' },
  'Overland Park': { country: 'USA', stateProvince: 'Kansas' },
  'Topeka': { country: 'USA', stateProvince: 'Kansas' },
  'Lexington': { country: 'USA', stateProvince: 'Kentucky' },
  'Shreveport': { country: 'USA', stateProvince: 'Louisiana' },
  'Bangor': { country: 'USA', stateProvince: 'Maine' },
  'Annapolis': { country: 'USA', stateProvince: 'Maryland' },
  'Frederick': { country: 'USA', stateProvince: 'Maryland' },
  'Worcester': { country: 'USA', stateProvince: 'Massachusetts' },
  'Cambridge': { country: 'USA', stateProvince: 'Massachusetts' },
  'Lowell': { country: 'USA', stateProvince: 'Massachusetts' },
  'Grand Rapids': { country: 'USA', stateProvince: 'Michigan' },
  'Warren': { country: 'USA', stateProvince: 'Michigan' },
  'Sterling Heights': { country: 'USA', stateProvince: 'Michigan' },
  'Ann Arbor': { country: 'USA', stateProvince: 'Michigan' },
  'Lansing': { country: 'USA', stateProvince: 'Michigan' },
  'St. Paul': { country: 'USA', stateProvince: 'Minnesota' },
  'Rochester': { country: 'USA', stateProvince: 'Minnesota' },
  'Duluth': { country: 'USA', stateProvince: 'Minnesota' },
  'Gulfport': { country: 'USA', stateProvince: 'Mississippi' },
  'Billings': { country: 'USA', stateProvince: 'Montana' },
  'Missoula': { country: 'USA', stateProvince: 'Montana' },
  'Lincoln': { country: 'USA', stateProvince: 'Nebraska' },
  'Bellevue': { country: 'USA', stateProvince: 'Nebraska' },
  'Henderson': { country: 'USA', stateProvince: 'Nevada' },
  'North Las Vegas': { country: 'USA', stateProvince: 'Nevada' },
  'Nashua': { country: 'USA', stateProvince: 'New Hampshire' },
  'Jersey City': { country: 'USA', stateProvince: 'New Jersey' },
  'Paterson': { country: 'USA', stateProvince: 'New Jersey' },
  'Elizabeth': { country: 'USA', stateProvince: 'New Jersey' },
  'Las Cruces': { country: 'USA', stateProvince: 'New Mexico' },
  'Santa Fe': { country: 'USA', stateProvince: 'New Mexico' },
  'Buffalo': { country: 'USA', stateProvince: 'New York' },
  'Yonkers': { country: 'USA', stateProvince: 'New York' },
  'Syracuse': { country: 'USA', stateProvince: 'New York' },
  'Albany': { country: 'USA', stateProvince: 'New York' },
  'Greensboro': { country: 'USA', stateProvince: 'North Carolina' },
  'Durham': { country: 'USA', stateProvince: 'North Carolina' },
  'Winston-Salem': { country: 'USA', stateProvince: 'North Carolina' },
  'Fargo': { country: 'USA', stateProvince: 'North Dakota' },
  'Bismarck': { country: 'USA', stateProvince: 'North Dakota' },
  'Cleveland': { country: 'USA', stateProvince: 'Ohio' },
  'Cincinnati': { country: 'USA', stateProvince: 'Ohio' },
  'Toledo': { country: 'USA', stateProvince: 'Ohio' },
  'Akron': { country: 'USA', stateProvince: 'Ohio' },
  'Dayton': { country: 'USA', stateProvince: 'Ohio' },
  'Eugene': { country: 'USA', stateProvince: 'Oregon' },
  'Salem': { country: 'USA', stateProvince: 'Oregon' },
  'Gresham': { country: 'USA', stateProvince: 'Oregon' },
  'Pittsburgh': { country: 'USA', stateProvince: 'Pennsylvania' },
  'Allentown': { country: 'USA', stateProvince: 'Pennsylvania' },
  'Erie': { country: 'USA', stateProvince: 'Pennsylvania' },
  'Warwick': { country: 'USA', stateProvince: 'Rhode Island' },
  'North Charleston': { country: 'USA', stateProvince: 'South Carolina' },
  'Sioux Falls': { country: 'USA', stateProvince: 'South Dakota' },
  'Rapid City': { country: 'USA', stateProvince: 'South Dakota' },
  'Knoxville': { country: 'USA', stateProvince: 'Tennessee' },
  'Chattanooga': { country: 'USA', stateProvince: 'Tennessee' },
  'Clarksville': { country: 'USA', stateProvince: 'Tennessee' },
  'Murfreesboro': { country: 'USA', stateProvince: 'Tennessee' },
  'Laredo': { country: 'USA', stateProvince: 'Texas' },
  'Lubbock': { country: 'USA', stateProvince: 'Texas' },
  'Plano': { country: 'USA', stateProvince: 'Texas' },
  'Irving': { country: 'USA', stateProvince: 'Texas' },
  'Garland': { country: 'USA', stateProvince: 'Texas' },
  'Corpus Christi': { country: 'USA', stateProvince: 'Texas' },
  'Amarillo': { country: 'USA', stateProvince: 'Texas' },
  'Grand Prairie': { country: 'USA', stateProvince: 'Texas' },
  'Brownsville': { country: 'USA', stateProvince: 'Texas' },
  'McKinney': { country: 'USA', stateProvince: 'Texas' },
  'Frisco': { country: 'USA', stateProvince: 'Texas' },
  'Salt Lake City': { country: 'USA', stateProvince: 'Utah' },
  'West Valley City': { country: 'USA', stateProvince: 'Utah' },
  'Provo': { country: 'USA', stateProvince: 'Utah' },
  'Ogden': { country: 'USA', stateProvince: 'Utah' },
  'Burlington': { country: 'USA', stateProvince: 'Vermont' },
  'Montpelier': { country: 'USA', stateProvince: 'Vermont' },
  'Norfolk': { country: 'USA', stateProvince: 'Virginia' },
  'Chesapeake': { country: 'USA', stateProvince: 'Virginia' },
  'Richmond': { country: 'USA', stateProvince: 'Virginia' },
  'Newport News': { country: 'USA', stateProvince: 'Virginia' },
  'Huntington': { country: 'USA', stateProvince: 'West Virginia' },
  'Madison': { country: 'USA', stateProvince: 'Wisconsin' },
  'Green Bay': { country: 'USA', stateProvince: 'Wisconsin' },
  'Kenosha': { country: 'USA', stateProvince: 'Wisconsin' },
  'Cheyenne': { country: 'USA', stateProvince: 'Wyoming' },
  'Casper': { country: 'USA', stateProvince: 'Wyoming' },
};
