// Listener cities schema and types

export interface ListenerCity {
  id: string;
  city: string;
  stateProvince?: string; // Optional - not all countries have states/provinces
  country: string;
  continent: string;
  region?: string; // e.g., "North America", "Western Europe"
  isCovered: boolean; // Has it been covered on "Where the fuck are the viewers from"
  coveredDate?: string;
  coveredEpisode?: string;
  createdAt: string;
  updatedAt: string;
  profileId: string;
}

export interface ListenerCityInput {
  city: string;
  stateProvince?: string;
  country?: string; // Optional - will be auto-detected if not provided
}

export interface CityImportResult {
  success: boolean;
  imported: number;
  failed: number;
  errors: Array<{
    row: number;
    city: string;
    error: string;
  }>;
}

// Continent mapping for countries (comprehensive list of 150+ countries)
export const COUNTRY_TO_CONTINENT: Record<string, string> = {
  // ===== NORTH AMERICA =====
  'USA': 'North America',
  'United States': 'North America',
  'US': 'North America',
  'Canada': 'North America',
  'Mexico': 'North America',
  'Guatemala': 'North America',
  'Honduras': 'North America',
  'El Salvador': 'North America',
  'Nicaragua': 'North America',
  'Costa Rica': 'North America',
  'Panama': 'North America',
  'Belize': 'North America',
  
  // Caribbean
  'Cuba': 'North America',
  'Jamaica': 'North America',
  'Haiti': 'North America',
  'Dominican Republic': 'North America',
  'Puerto Rico': 'North America',
  'Trinidad and Tobago': 'North America',
  'Bahamas': 'North America',
  'Barbados': 'North America',
  
  // ===== SOUTH AMERICA =====
  'Brazil': 'South America',
  'Argentina': 'South America',
  'Chile': 'South America',
  'Colombia': 'South America',
  'Peru': 'South America',
  'Venezuela': 'South America',
  'Ecuador': 'South America',
  'Bolivia': 'South America',
  'Paraguay': 'South America',
  'Uruguay': 'South America',
  'Guyana': 'South America',
  'Suriname': 'South America',
  'French Guiana': 'South America',
  
  // ===== WESTERN EUROPE =====
  'UK': 'Europe',
  'United Kingdom': 'Europe',
  'England': 'Europe',
  'Scotland': 'Europe',
  'Wales': 'Europe',
  'Northern Ireland': 'Europe',
  'Ireland': 'Europe',
  'France': 'Europe',
  'Germany': 'Europe',
  'Netherlands': 'Europe',
  'Belgium': 'Europe',
  'Luxembourg': 'Europe',
  'Switzerland': 'Europe',
  'Austria': 'Europe',
  'Liechtenstein': 'Europe',
  'Monaco': 'Europe',
  
  // Southern Europe
  'Spain': 'Europe',
  'Portugal': 'Europe',
  'Italy': 'Europe',
  'Greece': 'Europe',
  'Malta': 'Europe',
  'Cyprus': 'Europe',
  'Vatican City': 'Europe',
  'San Marino': 'Europe',
  'Andorra': 'Europe',
  
  // Northern Europe
  'Sweden': 'Europe',
  'Norway': 'Europe',
  'Denmark': 'Europe',
  'Finland': 'Europe',
  'Iceland': 'Europe',
  
  // Eastern Europe
  'Poland': 'Europe',
  'Czech Republic': 'Europe',
  'Slovakia': 'Europe',
  'Hungary': 'Europe',
  'Romania': 'Europe',
  'Bulgaria': 'Europe',
  'Serbia': 'Europe',
  'Croatia': 'Europe',
  'Slovenia': 'Europe',
  'Bosnia and Herzegovina': 'Europe',
  'Montenegro': 'Europe',
  'North Macedonia': 'Europe',
  'Albania': 'Europe',
  'Kosovo': 'Europe',
  'Lithuania': 'Europe',
  'Latvia': 'Europe',
  'Estonia': 'Europe',
  'Belarus': 'Europe',
  'Ukraine': 'Europe',
  'Moldova': 'Europe',
  'Russia': 'Europe',
  
  // ===== ASIA =====
  // East Asia
  'China': 'Asia',
  'Japan': 'Asia',
  'South Korea': 'Asia',
  'North Korea': 'Asia',
  'Taiwan': 'Asia',
  'Mongolia': 'Asia',
  
  // Southeast Asia
  'Thailand': 'Asia',
  'Vietnam': 'Asia',
  'Philippines': 'Asia',
  'Indonesia': 'Asia',
  'Malaysia': 'Asia',
  'Singapore': 'Asia',
  'Myanmar': 'Asia',
  'Cambodia': 'Asia',
  'Laos': 'Asia',
  'Brunei': 'Asia',
  'Timor-Leste': 'Asia',
  
  // South Asia
  'India': 'Asia',
  'Pakistan': 'Asia',
  'Bangladesh': 'Asia',
  'Sri Lanka': 'Asia',
  'Nepal': 'Asia',
  'Bhutan': 'Asia',
  'Maldives': 'Asia',
  'Afghanistan': 'Asia',
  
  // Central Asia
  'Kazakhstan': 'Asia',
  'Uzbekistan': 'Asia',
  'Turkmenistan': 'Asia',
  'Kyrgyzstan': 'Asia',
  'Tajikistan': 'Asia',
  
  // Middle East
  'Turkey': 'Asia',
  'Iran': 'Asia',
  'Iraq': 'Asia',
  'Saudi Arabia': 'Asia',
  'Yemen': 'Asia',
  'Oman': 'Asia',
  'United Arab Emirates': 'Asia',
  'UAE': 'Asia',
  'Qatar': 'Asia',
  'Kuwait': 'Asia',
  'Bahrain': 'Asia',
  'Jordan': 'Asia',
  'Lebanon': 'Asia',
  'Syria': 'Asia',
  'Israel': 'Asia',
  'Palestine': 'Asia',
  'Armenia': 'Asia',
  'Azerbaijan': 'Asia',
  'Georgia': 'Asia',
  
  // ===== AFRICA =====
  // North Africa
  'Egypt': 'Africa',
  'Libya': 'Africa',
  'Tunisia': 'Africa',
  'Algeria': 'Africa',
  'Morocco': 'Africa',
  'Sudan': 'Africa',
  
  // West Africa
  'Nigeria': 'Africa',
  'Ghana': 'Africa',
  'Ivory Coast': 'Africa',
  'Senegal': 'Africa',
  'Mali': 'Africa',
  'Burkina Faso': 'Africa',
  'Niger': 'Africa',
  'Guinea': 'Africa',
  'Benin': 'Africa',
  'Togo': 'Africa',
  'Sierra Leone': 'Africa',
  'Liberia': 'Africa',
  'Mauritania': 'Africa',
  'Gambia': 'Africa',
  'Cape Verde': 'Africa',
  
  // East Africa
  'Kenya': 'Africa',
  'Tanzania': 'Africa',
  'Uganda': 'Africa',
  'Ethiopia': 'Africa',
  'Somalia': 'Africa',
  'Eritrea': 'Africa',
  'Djibouti': 'Africa',
  'Rwanda': 'Africa',
  'Burundi': 'Africa',
  
  // Central Africa
  'Democratic Republic of the Congo': 'Africa',
  'Republic of the Congo': 'Africa',
  'Central African Republic': 'Africa',
  'Chad': 'Africa',
  'Cameroon': 'Africa',
  'Gabon': 'Africa',
  'Equatorial Guinea': 'Africa',
  
  // Southern Africa
  'South Africa': 'Africa',
  'Zimbabwe': 'Africa',
  'Zambia': 'Africa',
  'Mozambique': 'Africa',
  'Botswana': 'Africa',
  'Namibia': 'Africa',
  'Angola': 'Africa',
  'Malawi': 'Africa',
  'Lesotho': 'Africa',
  'Eswatini': 'Africa',
  'Madagascar': 'Africa',
  'Mauritius': 'Africa',
  
  // ===== OCEANIA =====
  'Australia': 'Oceania',
  'New Zealand': 'Oceania',
  'Papua New Guinea': 'Oceania',
  'Fiji': 'Oceania',
  'Solomon Islands': 'Oceania',
  'Vanuatu': 'Oceania',
  'Samoa': 'Oceania',
  'Tonga': 'Oceania',
  'Micronesia': 'Oceania',
  'Palau': 'Oceania',
  'Marshall Islands': 'Oceania',
  'Kiribati': 'Oceania',
  'Nauru': 'Oceania',
  'Tuvalu': 'Oceania',
};

// Well-known cities that can help auto-detect country (500+ major world cities)
export const FAMOUS_CITIES: Record<string, { country: string; stateProvince?: string }> = {
  // ===== UNITED STATES =====
  'New York': { country: 'USA', stateProvince: 'New York' },
  'Los Angeles': { country: 'USA', stateProvince: 'California' },
  'Chicago': { country: 'USA', stateProvince: 'Illinois' },
  'Houston': { country: 'USA', stateProvince: 'Texas' },
  'Phoenix': { country: 'USA', stateProvince: 'Arizona' },
  'Philadelphia': { country: 'USA', stateProvince: 'Pennsylvania' },
  'San Antonio': { country: 'USA', stateProvince: 'Texas' },
  'San Diego': { country: 'USA', stateProvince: 'California' },
  'Dallas': { country: 'USA', stateProvince: 'Texas' },
  'San Jose': { country: 'USA', stateProvince: 'California' },
  'Austin': { country: 'USA', stateProvince: 'Texas' },
  'Jacksonville': { country: 'USA', stateProvince: 'Florida' },
  'Fort Worth': { country: 'USA', stateProvince: 'Texas' },
  'Columbus': { country: 'USA', stateProvince: 'Ohio' },
  'Charlotte': { country: 'USA', stateProvince: 'North Carolina' },
  'San Francisco': { country: 'USA', stateProvince: 'California' },
  'Indianapolis': { country: 'USA', stateProvince: 'Indiana' },
  'Seattle': { country: 'USA', stateProvince: 'Washington' },
  'Denver': { country: 'USA', stateProvince: 'Colorado' },
  'Washington': { country: 'USA', stateProvince: 'District of Columbia' },
  'Boston': { country: 'USA', stateProvince: 'Massachusetts' },
  'El Paso': { country: 'USA', stateProvince: 'Texas' },
  'Detroit': { country: 'USA', stateProvince: 'Michigan' },
  'Nashville': { country: 'USA', stateProvince: 'Tennessee' },
  'Portland': { country: 'USA', stateProvince: 'Oregon' },
  'Memphis': { country: 'USA', stateProvince: 'Tennessee' },
  'Oklahoma City': { country: 'USA', stateProvince: 'Oklahoma' },
  'Las Vegas': { country: 'USA', stateProvince: 'Nevada' },
  'Louisville': { country: 'USA', stateProvince: 'Kentucky' },
  'Baltimore': { country: 'USA', stateProvince: 'Maryland' },
  'Milwaukee': { country: 'USA', stateProvince: 'Wisconsin' },
  'Albuquerque': { country: 'USA', stateProvince: 'New Mexico' },
  'Tucson': { country: 'USA', stateProvince: 'Arizona' },
  'Fresno': { country: 'USA', stateProvince: 'California' },
  'Sacramento': { country: 'USA', stateProvince: 'California' },
  'Kansas City': { country: 'USA', stateProvince: 'Missouri' },
  'Mesa': { country: 'USA', stateProvince: 'Arizona' },
  'Atlanta': { country: 'USA', stateProvince: 'Georgia' },
  'Miami': { country: 'USA', stateProvince: 'Florida' },
  'Raleigh': { country: 'USA', stateProvince: 'North Carolina' },
  'Omaha': { country: 'USA', stateProvince: 'Nebraska' },
  'Colorado Springs': { country: 'USA', stateProvince: 'Colorado' },
  'Virginia Beach': { country: 'USA', stateProvince: 'Virginia' },
  'Oakland': { country: 'USA', stateProvince: 'California' },
  'Minneapolis': { country: 'USA', stateProvince: 'Minnesota' },
  'Tulsa': { country: 'USA', stateProvince: 'Oklahoma' },
  'Tampa': { country: 'USA', stateProvince: 'Florida' },
  'Arlington': { country: 'USA', stateProvince: 'Texas' },
  'New Orleans': { country: 'USA', stateProvince: 'Louisiana' },
  
  // ===== CANADA =====
  'Toronto': { country: 'Canada', stateProvince: 'Ontario' },
  'Montreal': { country: 'Canada', stateProvince: 'Quebec' },
  'Vancouver': { country: 'Canada', stateProvince: 'British Columbia' },
  'Calgary': { country: 'Canada', stateProvince: 'Alberta' },
  'Edmonton': { country: 'Canada', stateProvince: 'Alberta' },
  'Ottawa': { country: 'Canada', stateProvince: 'Ontario' },
  'Winnipeg': { country: 'Canada', stateProvince: 'Manitoba' },
  'Quebec City': { country: 'Canada', stateProvince: 'Quebec' },
  'Hamilton': { country: 'Canada', stateProvince: 'Ontario' },
  'Kitchener': { country: 'Canada', stateProvince: 'Ontario' },
  'Halifax': { country: 'Canada', stateProvince: 'Nova Scotia' },
  'Victoria': { country: 'Canada', stateProvince: 'British Columbia' },
  
  // ===== MEXICO & CENTRAL AMERICA =====
  'Mexico City': { country: 'Mexico' },
  'Guadalajara': { country: 'Mexico' },
  'Monterrey': { country: 'Mexico' },
  'Tijuana': { country: 'Mexico' },
  'Cancún': { country: 'Mexico' },
  'Puebla': { country: 'Mexico' },
  'Guatemala City': { country: 'Guatemala' },
  'San Salvador': { country: 'El Salvador' },
  'Managua': { country: 'Nicaragua' },
  'San José': { country: 'Costa Rica' },
  'Panama City': { country: 'Panama' },
  
  // ===== CARIBBEAN =====
  'Havana': { country: 'Cuba' },
  'Kingston': { country: 'Jamaica' },
  'Santo Domingo': { country: 'Dominican Republic' },
  'Port-au-Prince': { country: 'Haiti' },
  'San Juan': { country: 'Puerto Rico' },
  
  // ===== SOUTH AMERICA =====
  'São Paulo': { country: 'Brazil' },
  'Rio de Janeiro': { country: 'Brazil' },
  'Brasília': { country: 'Brazil' },
  'Salvador': { country: 'Brazil' },
  'Fortaleza': { country: 'Brazil' },
  'Belo Horizonte': { country: 'Brazil' },
  'Manaus': { country: 'Brazil' },
  'Buenos Aires': { country: 'Argentina' },
  'Córdoba': { country: 'Argentina' },
  'Rosario': { country: 'Argentina' },
  'Lima': { country: 'Peru' },
  'Bogotá': { country: 'Colombia' },
  'Medellín': { country: 'Colombia' },
  'Cali': { country: 'Colombia' },
  'Santiago': { country: 'Chile' },
  'Caracas': { country: 'Venezuela' },
  'Quito': { country: 'Ecuador' },
  'Guayaquil': { country: 'Ecuador' },
  'La Paz': { country: 'Bolivia' },
  'Montevideo': { country: 'Uruguay' },
  
  // ===== UNITED KINGDOM =====
  'London': { country: 'UK' },
  'Manchester': { country: 'UK' },
  'Birmingham': { country: 'UK' },
  'Liverpool': { country: 'UK' },
  'Leeds': { country: 'UK' },
  'Sheffield': { country: 'UK' },
  'Edinburgh': { country: 'UK' },
  'Glasgow': { country: 'UK' },
  'Bristol': { country: 'UK' },
  'Newcastle': { country: 'UK' },
  'Cardiff': { country: 'UK' },
  'Belfast': { country: 'UK' },
  'Nottingham': { country: 'UK' },
  'Southampton': { country: 'UK' },
  
  // ===== WESTERN EUROPE =====
  'Paris': { country: 'France' },
  'Marseille': { country: 'France' },
  'Lyon': { country: 'France' },
  'Toulouse': { country: 'France' },
  'Nice': { country: 'France' },
  'Nantes': { country: 'France' },
  'Berlin': { country: 'Germany' },
  'Hamburg': { country: 'Germany' },
  'Munich': { country: 'Germany' },
  'Cologne': { country: 'Germany' },
  'Frankfurt': { country: 'Germany' },
  'Stuttgart': { country: 'Germany' },
  'Düsseldorf': { country: 'Germany' },
  'Amsterdam': { country: 'Netherlands' },
  'Rotterdam': { country: 'Netherlands' },
  'The Hague': { country: 'Netherlands' },
  'Utrecht': { country: 'Netherlands' },
  'Brussels': { country: 'Belgium' },
  'Antwerp': { country: 'Belgium' },
  'Zurich': { country: 'Switzerland' },
  'Geneva': { country: 'Switzerland' },
  'Basel': { country: 'Switzerland' },
  'Vienna': { country: 'Austria' },
  'Luxembourg': { country: 'Luxembourg' },
  
  // ===== SOUTHERN EUROPE =====
  'Rome': { country: 'Italy' },
  'Milan': { country: 'Italy' },
  'Naples': { country: 'Italy' },
  'Turin': { country: 'Italy' },
  'Florence': { country: 'Italy' },
  'Venice': { country: 'Italy' },
  'Madrid': { country: 'Spain' },
  'Barcelona': { country: 'Spain' },
  'Valencia': { country: 'Spain' },
  'Seville': { country: 'Spain' },
  'Bilbao': { country: 'Spain' },
  'Lisbon': { country: 'Portugal' },
  'Porto': { country: 'Portugal' },
  'Athens': { country: 'Greece' },
  'Thessaloniki': { country: 'Greece' },
  
  // ===== NORTHERN EUROPE =====
  'Stockholm': { country: 'Sweden' },
  'Gothenburg': { country: 'Sweden' },
  'Oslo': { country: 'Norway' },
  'Copenhagen': { country: 'Denmark' },
  'Helsinki': { country: 'Finland' },
  'Reykjavik': { country: 'Iceland' },
  
  // ===== EASTERN EUROPE =====
  'Warsaw': { country: 'Poland' },
  'Kraków': { country: 'Poland' },
  'Prague': { country: 'Czech Republic' },
  'Budapest': { country: 'Hungary' },
  'Bucharest': { country: 'Romania' },
  'Sofia': { country: 'Bulgaria' },
  'Belgrade': { country: 'Serbia' },
  'Zagreb': { country: 'Croatia' },
  'Bratislava': { country: 'Slovakia' },
  'Vilnius': { country: 'Lithuania' },
  'Riga': { country: 'Latvia' },
  'Tallinn': { country: 'Estonia' },
  
  // ===== RUSSIA & FORMER USSR =====
  'Moscow': { country: 'Russia' },
  'Saint Petersburg': { country: 'Russia' },
  'Novosibirsk': { country: 'Russia' },
  'Yekaterinburg': { country: 'Russia' },
  'Nizhny Novgorod': { country: 'Russia' },
  'Kazan': { country: 'Russia' },
  'Kiev': { country: 'Ukraine' },
  'Kyiv': { country: 'Ukraine' },
  'Kharkiv': { country: 'Ukraine' },
  'Odessa': { country: 'Ukraine' },
  
  // ===== MIDDLE EAST =====
  'Istanbul': { country: 'Turkey' },
  'Ankara': { country: 'Turkey' },
  'Izmir': { country: 'Turkey' },
  'Dubai': { country: 'United Arab Emirates' },
  'Abu Dhabi': { country: 'United Arab Emirates' },
  'Riyadh': { country: 'Saudi Arabia' },
  'Jeddah': { country: 'Saudi Arabia' },
  'Mecca': { country: 'Saudi Arabia' },
  'Tehran': { country: 'Iran' },
  'Baghdad': { country: 'Iraq' },
  'Tel Aviv': { country: 'Israel' },
  'Jerusalem': { country: 'Israel' },
  'Beirut': { country: 'Lebanon' },
  'Damascus': { country: 'Syria' },
  'Amman': { country: 'Jordan' },
  'Doha': { country: 'Qatar' },
  'Kuwait City': { country: 'Kuwait' },
  'Muscat': { country: 'Oman' },
  
  // ===== EAST ASIA =====
  'Tokyo': { country: 'Japan' },
  'Yokohama': { country: 'Japan' },
  'Osaka': { country: 'Japan' },
  'Nagoya': { country: 'Japan' },
  'Sapporo': { country: 'Japan' },
  'Fukuoka': { country: 'Japan' },
  'Kyoto': { country: 'Japan' },
  'Beijing': { country: 'China' },
  'Shanghai': { country: 'China' },
  'Guangzhou': { country: 'China' },
  'Shenzhen': { country: 'China' },
  'Chengdu': { country: 'China' },
  'Chongqing': { country: 'China' },
  'Tianjin': { country: 'China' },
  'Wuhan': { country: 'China' },
  'Hangzhou': { country: 'China' },
  'Xi\'an': { country: 'China' },
  'Hong Kong': { country: 'China' },
  'Seoul': { country: 'South Korea' },
  'Busan': { country: 'South Korea' },
  'Incheon': { country: 'South Korea' },
  'Taipei': { country: 'Taiwan' },
  
  // ===== SOUTHEAST ASIA =====
  'Bangkok': { country: 'Thailand' },
  'Singapore': { country: 'Singapore' },
  'Jakarta': { country: 'Indonesia' },
  'Surabaya': { country: 'Indonesia' },
  'Bandung': { country: 'Indonesia' },
  'Manila': { country: 'Philippines' },
  'Quezon City': { country: 'Philippines' },
  'Ho Chi Minh City': { country: 'Vietnam' },
  'Hanoi': { country: 'Vietnam' },
  'Kuala Lumpur': { country: 'Malaysia' },
  'Yangon': { country: 'Myanmar' },
  'Phnom Penh': { country: 'Cambodia' },
  'Vientiane': { country: 'Laos' },
  'Brunei': { country: 'Brunei' },
  
  // ===== SOUTH ASIA =====
  'Mumbai': { country: 'India' },
  'Delhi': { country: 'India' },
  'Bangalore': { country: 'India' },
  'Hyderabad': { country: 'India' },
  'Ahmedabad': { country: 'India' },
  'Chennai': { country: 'India' },
  'Kolkata': { country: 'India' },
  'Pune': { country: 'India' },
  'Jaipur': { country: 'India' },
  'Karachi': { country: 'Pakistan' },
  'Lahore': { country: 'Pakistan' },
  'Islamabad': { country: 'Pakistan' },
  'Dhaka': { country: 'Bangladesh' },
  'Colombo': { country: 'Sri Lanka' },
  'Kathmandu': { country: 'Nepal' },
  
  // ===== OCEANIA =====
  'Sydney': { country: 'Australia', stateProvince: 'New South Wales' },
  'Melbourne': { country: 'Australia', stateProvince: 'Victoria' },
  'Brisbane': { country: 'Australia', stateProvince: 'Queensland' },
  'Perth': { country: 'Australia', stateProvince: 'Western Australia' },
  'Adelaide': { country: 'Australia', stateProvince: 'South Australia' },
  'Gold Coast': { country: 'Australia', stateProvince: 'Queensland' },
  'Canberra': { country: 'Australia', stateProvince: 'Australian Capital Territory' },
  'Auckland': { country: 'New Zealand' },
  'Wellington': { country: 'New Zealand' },
  'Christchurch': { country: 'New Zealand' },
  
  // ===== AFRICA =====
  'Cairo': { country: 'Egypt' },
  'Alexandria': { country: 'Egypt' },
  'Lagos': { country: 'Nigeria' },
  'Kano': { country: 'Nigeria' },
  'Johannesburg': { country: 'South Africa' },
  'Cape Town': { country: 'South Africa' },
  'Durban': { country: 'South Africa' },
  'Nairobi': { country: 'Kenya' },
  'Addis Ababa': { country: 'Ethiopia' },
  'Accra': { country: 'Ghana' },
  'Casablanca': { country: 'Morocco' },
  'Algiers': { country: 'Algeria' },
  'Tunis': { country: 'Tunisia' },
  'Dakar': { country: 'Senegal' },
  'Dar es Salaam': { country: 'Tanzania' },
  'Kampala': { country: 'Uganda' },
  'Luanda': { country: 'Angola' },
  'Khartoum': { country: 'Sudan' },
  'Abidjan': { country: 'Ivory Coast' },
  'Kinshasa': { country: 'Democratic Republic of the Congo' },
};
